name: LOWER_PROJ_NAME
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=PYTHON_VERSION
  - conda
  - git
  - pip>=24.2
  - setuptools
  - wheel
  - menuinst>=2
  - truststore>=0.10.4
  - certifi
  - jupyterlab=JUPYTERLAB_VERSION
